### ISSUE TITLE
ensembl-tui roadmap sketch

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/ensembl_cli#38]
# Minimal usability

> **Note**
> This means the tool can be installed and used to download and install data from ensembl.org necessary to perform the selected set of queries defined below. These queries will produce standard formats. **This variant will have a lot of errors!**

- [x] terminal interface for controlling primary functions
- [x] given a config, can get sequences, gff3, and alignments from Ensembl.org
- [x] above is transformed to a "local" install via sqlite databases
- [x] dump-genes command generates a tsv formatted file for a species
- [x] export one-to-one homologs as fasta
- [x] display installed data in the terminal
- [x] dump alignment segments corresponding to a user provided input list of genomic regions / genes
- [x] mask segments of exported alignments for selected feature types (e.g. exons)

[Track progress on the issues page](https://github.com/cogent3/EnsemblLite/issues?q=is%3Aopen+is%3Aissue+milestone%3Aminimal-usability)

# Robust usability

> **Note**
> Same feature set as above, but now the tool has a test coverage of ~90% and internals have been refactored for clarity. We will call for testers at this point. **This variant will have some errors!**

- [x] supported annotations extended to include repeats, CpG islands (see #65)
- [x] ~90% of all code lines are evaluated with tests
- [x] homolog querying expanded to different relationship types (e.g. ortholog one-to-many, paralogs)
- [x] scitrack logging will be added
- [x] minimal documentation

[Track progress on the issues page](https://github.com/cogent3/EnsemblLite/issues?q=is%3Aopen+is%3Aissue+milestone%3Arobust-usability)
